[package]
name = "switch-user"
version = "0.1.0"
authors = ["Alpha Chen <alpha@kejadlen.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
